# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  JOINT_ANKLE_PITCH_L:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_ANKLE_PITCH_R:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_ANKLE_ROLL_L:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_ANKLE_ROLL_R:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_HIP_PITCH_L:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_HIP_PITCH_R:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_HIP_ROLL_L:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_HIP_ROLL_R:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_HIP_YAW_L:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_HIP_YAW_R:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_KNEE_PITCH_L:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  JOINT_KNEE_PITCH_R:
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_la1:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_la2:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_la3:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_la4:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_la5:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_la6:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_la7:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_ra1:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_ra2:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_ra3:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_ra4:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_ra5:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_ra6:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
  joint_ra7:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: false
    max_acceleration: 0
