# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - joint_la1
      - joint_la2
      - joint_la3
      - joint_la4
      - joint_la5
      - joint_la6
      - joint_la7
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - joint_ra1
      - joint_ra2
      - joint_ra3
      - joint_ra4
      - joint_ra5
      - joint_ra6
      - joint_ra7
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
left_leg_controller:
  ros__parameters:
    joints:
      - JOINT_HIP_ROLL_L
      - JOINT_HIP_YAW_L
      - JOINT_HIP_PITCH_L
      - JOINT_KNEE_PITCH_L
      - JOINT_ANKLE_PITCH_L
      - JOINT_ANKLE_ROLL_L
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
right_leg_controller:
  ros__parameters:
    joints:
      - JOINT_HIP_ROLL_R
      - JOINT_HIP_YAW_R
      - JOINT_HIP_PITCH_R
      - JOINT_KNEE_PITCH_R
      - JOINT_ANKLE_PITCH_R
      - JOINT_ANKLE_ROLL_R
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity